create database `czhl_service_sign_in`;

use `czhl_service_sign_in`;

CREATE TABLE `device` (
                          `id` bigint NOT NULL AUTO_INCREMENT,
                          `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                          `version` int DEFAULT '1' COMMENT '乐观锁,默认为1',
                          `create_time` datetime DEFAULT NULL COMMENT '创建时',
                          `update_time` datetime DEFAULT NULL COMMENT '修改时',
                          `creator` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人uuid',
                          `editor` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人uuid',
                          `deleted` tinyint DEFAULT '0' COMMENT '逻辑删除,默认为false',
                          `institution_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '机构uuid',
                          `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '名称',
                          `number_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备sn码',
                          `area_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地址',
                          `enable` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '是否启用',
                          `number` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备编号',
                          `area_uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地址uuid',
                          `area_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地址code',
                          PRIMARY KEY (`id`),
                          UNIQUE KEY `unique_uuid` (`uuid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `sign_in_record` (
                                  `id` int NOT NULL AUTO_INCREMENT,
                                  `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                  `version` int DEFAULT '1' COMMENT '乐观锁,默认为1',
                                  `create_time` datetime DEFAULT NULL COMMENT '打卡日期时间',
                                  `update_time` datetime DEFAULT NULL COMMENT '修改时',
                                  `creator` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人uuid',
                                  `editor` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人uuid',
                                  `deleted` tinyint DEFAULT '0' COMMENT '逻辑删除,默认为false',
                                  `sign_task_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务uuid',
                                  `user_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '打卡用户uuid',
                                  `area_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到地点',
                                  `sign_image_url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到照片url',
                                  `push` tinyint DEFAULT '0' COMMENT '默认为0未推送',
                                  `number_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到设备sn',
                                  `body_temperature` float(5,1) DEFAULT NULL COMMENT '体感温度',
  `username` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用户名',
  `device_uuid` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备uuid',
  `status` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0,未签,1,已签,2,补签',
  `task_start_time` time DEFAULT NULL COMMENT '任务开始时间',
  `task_end_time` time DEFAULT NULL COMMENT '任务开始时间',
  `task_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到时段名称',
  `area_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地点uuid',
  `sign_statistics_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '统计uuid',
  `institution_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '机构uuid',
  `is_enable` bigint DEFAULT '0' COMMENT '开启',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_uuid` (`uuid`) USING BTREE,
  KEY `task_user` (`sign_task_uuid`,`user_uuid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `sign_in_task` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '签到任务uuid',
                                `version` int DEFAULT '1' COMMENT '乐观锁,默认为1',
                                `create_time` datetime DEFAULT NULL COMMENT '签到时间',
                                `update_time` datetime DEFAULT NULL COMMENT '修改时',
                                `creator` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
                                `editor` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
                                `deleted` tinyint DEFAULT '0' COMMENT '逻辑删除,默认为false',
                                `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到任务名称',
                                `user_uuids` json DEFAULT NULL COMMENT '所有待签到人员',
                                `polling_mode` int DEFAULT NULL COMMENT '循环模式,1,日,7周循环',
                                `week` json DEFAULT NULL COMMENT '签到日',
                                `task_start_time` time DEFAULT NULL COMMENT '签到任务开始时间',
                                `task_end_time` time DEFAULT NULL COMMENT '签到任务结束时间',
                                `task_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到时间段名称',
                                `task_start_date` date DEFAULT NULL COMMENT '有效开始日期',
                                `task_end_date` date DEFAULT NULL COMMENT '有效结束日期',
                                `device_uuids` json DEFAULT NULL COMMENT '终端',
                                `status` tinyint DEFAULT '1' COMMENT '状态,进行中为1,已失效0',
                                `device_sns` json DEFAULT NULL COMMENT '终端sn',
                                `sign_in_mode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '打卡模式0,人脸,1定位',
                                `push` tinyint DEFAULT '0' COMMENT '签到推送',
                                `more_config` json DEFAULT NULL COMMENT '其他配置',
                                `filter_festival` tinyint DEFAULT '0' COMMENT '是否过滤节假日',
                                `is_enable` tinyint DEFAULT '1' COMMENT '开启',
                                `institution_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '机构uuid',
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `unique_uuid` (`uuid`) USING BTREE,
                                KEY `task_name_bo` (`task_start_time`,`task_end_time`,`task_name`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `sign_statistics` (
                                   `id` bigint NOT NULL AUTO_INCREMENT,
                                   `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                   `version` int DEFAULT '1' COMMENT '乐观锁,默认为1',
                                   `create_time` datetime DEFAULT NULL COMMENT '创建时',
                                   `update_time` datetime DEFAULT NULL COMMENT '修改时',
                                   `creator` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人uuid',
                                   `editor` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人uuid',
                                   `deleted` tinyint DEFAULT '0' COMMENT '逻辑删除,默认为false',
                                   `task_start_time` time DEFAULT NULL COMMENT '任务开始时间',
                                   `task_end_time` time DEFAULT NULL COMMENT '任务开始时间',
                                   `task_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '签到时段名称',
                                   `task_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '任务uuid',
                                   `all_user` json DEFAULT NULL COMMENT '应签用户',
                                   `already_user` json DEFAULT NULL COMMENT '已签用户',
                                   `re_user` json DEFAULT NULL COMMENT '补签用户',
                                   `not_user` json DEFAULT NULL COMMENT '未签用户',
                                   `ask_leave_user` json DEFAULT NULL COMMENT '请假用户',
                                   `create_date` date DEFAULT NULL COMMENT '任务日期',
                                   `is_enable` tinyint DEFAULT '0' COMMENT '是否展示',
                                   `institution_uuid` varchar(36) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '机构uuid',
                                   PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `user` (
                        `id` int NOT NULL AUTO_INCREMENT,
                        `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户uuid',
                        `version` int DEFAULT '1' COMMENT '乐观锁,默认为1',
                        `create_time` datetime DEFAULT NULL COMMENT '创建时',
                        `update_time` datetime DEFAULT NULL COMMENT '修改时',
                        `creator` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人uuid',
                        `editor` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人uuid',
                        `deleted` tinyint DEFAULT '0' COMMENT '逻辑删除,默认为false',
                        `name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '姓名',
                        `gender` tinyint DEFAULT NULL COMMENT '性别,0:女,1,男',
                        `user_type` int DEFAULT NULL COMMENT '用户类型',
                        `phone` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                        `photo` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '照片url',
                        `head_url` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '头像url',
                        `nickname` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '昵称',
                        `organization_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '组织名称',
                        `organization_uuid` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '组织uuid',
                        PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;